In [2]:
import numpy as np

In [19]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)


In [20]:
print(a)
print(b)
c = a*b
print(c)

[[-0.34039516 -0.11250715  0.49958919]
 [-0.64891445 -1.06653971 -0.17579033]
 [-1.76787655 -0.46563522  1.29609513]]
[[0.19473881]
 [2.55112287]
 [1.31405142]]
[[-0.06628815 -0.02190951  0.0972894 ]
 [-1.65546048 -2.72087385 -0.44846272]
 [-2.32308069 -0.61186862  1.70313565]]


In [26]:
a = np.random.randn(1, 3)
b = np.random.randn(3, 3)
a_reshaped = a.flatten().reshape((3,))
c = a_reshaped * b
print(c.shape)  # Output: (3, 3)


(3, 3)


In [27]:
print(a)

[[-0.02163093 -0.68094666  0.59913386]]


In [3]:
a = np.array([10,23,21,32,42,442])

In [9]:
b = np.clip(a,0,20)
b = 2*b

In [10]:
print(b)

[20 40 40 40 40 40]
